import sys
input=sys.stdin.readline
n=int(input())
s=[]
for i in range(n):
    args=input().split()
    if(len(args)!=1):
        a,b=args[0],int(args[1])
        if(a=='push'):
            s.append(b)
        continue
    else:
        a=args[0]
        if(a=='pop'):
            if(len(s)!=0):
                print(s[-1])
                s.pop()
            else:
                print(-1)
        elif(a=='size'):
            print(len(s))
        elif(a=='empty'):
            if(len(s)==0):
                print(1)
            else:
                print(0)
        elif(a=='top'):
            if(len(s)==0):
                print(-1)
            else:
                print(s[-1])